### ISSUE TITLE
Logo Proposal for mTasks

### ISSUE THREAD

**Issue by mdnazmulhasan27771** [CodeBull/mTasks#1]
Hello,
This my logo/Icon design for your project.I design this logo using adobe illustrator cc 2017. I hope you like this logo

![mtasks](https://user-images.githubusercontent.com/35112507/38422559-06dc7228-39cd-11e8-814c-91cb2fb7b12e.png)

If you need anything change please contact me

Md Nazmul Hasan
Email : mdnazmul.hasan27771@gmail.com

Thank You.

**Comment by CodeBull** [comment]
Thank you for creating this logo. I am not looking for a logo now as the project name could change or I may want to purchase another domain and start building on that. It would be bad if I market it now later shift to something else.

But when I will require one, I'll definitely ping you.
